log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-rke2r0
      # renovate: datasource=github-tags depName=rancher/rke2 versioning=regex:^v(?<major>1)\.(?<minor>34)\.(?<patch>\d+)\+rke2r(?<build>\d+)$
      rke2_version: v1.34.4+rke2r1
      rke2_sha_amd64: 7f350b4ffbb3374cfe49337a90617d6e76d3bf1dd231208351151e5b421c3761
      rke2_sha_arm64: 81f9d36f575a4cbbd68687651f0befb208e080955f8568b135582f6bcb84e2e2
