log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-rke2r0
      # renovate: datasource=github-tags depName=rancher/rke2 versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\+rke2r(?<build>\d+)$
      rke2_version: v1.35.0+rke2r1
      rke2_sha_amd64: ade19659f6e655e8125471134b6d343f972d2aa7b6ec33cfd9c7805ac2715f4a
      rke2_sha_arm64: fec7c5010214eee9a596bb7c51cbc83ed36224fb2bb3bdc8b2de40805e5ae51a
