log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-rke2r0
      # renovate: datasource=github-tags depName=rancher/rke2 versioning=regex:^v(?<major>1)\.(?<minor>34)\.(?<patch>\d+)\+rke2r(?<build>\d+)$
      rke2_version: v1.34.3+rke2r1
      rke2_sha_amd64: bb83f6cc9e3e11c88883401d8d0cf3fde6d9d3c4925019229efaa77b4369c02d
      rke2_sha_arm64: 38bba88b6eff993f0c2568a0e95b1184dba8623b9a48b99bc5f868e76270581e
